[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 50
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
eth = "${RPC}"

[fuzz]
runs = 256