name: Forge Fuzz Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  fuzz:
    name: Forge Fuzz Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: |
          forge install OpenZeppelin/openzeppelin-contracts --no-commit
          forge install foundry-rs/forge-std --no-commit
          forge install uniswap/v3-core --no-commit
          forge install PaulRBerg/prb-math --no-commit
          forge install SquaredLab-io/v3-periphery --no-commit
          forge install smartcontractkit/chainlink-brownie-contracts@0.6.1 --no-commit
          forge install vectorized/solady --no-commit

      - name: Run Forge build
        run: |
          forge --version
          forge build
        
      - name: Run Forge fuzz tests
        run: |
          forge test --match-contract LongShortFuzz -vvv